# Generated by Django 4.2.5 on 2023-10-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_description', models.TextField()),
                ('bug_type', models.CharField(choices=[('error', 'error'), ('new feature', 'new feature'), ('code', 'code'), ('enhancement', 'enhancement')], max_length=50)),
                ('report_date', models.DateField()),
                ('status', models.CharField(choices=[('To do', 'To do'), ('In Progress', 'In Progress'), ('Done', 'Done')], max_length=50)),
            ],
        ),
    ]
